//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfSampleProject.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class sakilaEntities : DbContext
    {
        public sakilaEntities()
            : base("name=sakilaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<actor> actor { get; set; }
        public virtual DbSet<address> address { get; set; }
        public virtual DbSet<category> category { get; set; }
        public virtual DbSet<city> city { get; set; }
        public virtual DbSet<country> country { get; set; }
        public virtual DbSet<customer> customer { get; set; }
        public virtual DbSet<film> film { get; set; }
        public virtual DbSet<film_actor> film_actor { get; set; }
        public virtual DbSet<film_category> film_category { get; set; }
        public virtual DbSet<film_text> film_text { get; set; }
        public virtual DbSet<inventory> inventory { get; set; }
        public virtual DbSet<language> language { get; set; }
        public virtual DbSet<payment> payment { get; set; }
        public virtual DbSet<rental> rental { get; set; }
        public virtual DbSet<staff> staff { get; set; }
        public virtual DbSet<store> store { get; set; }
    }
}
